/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "functions.h"

uint8_t errState = 0;

int main(void)
{
	//uint8_t breakHandler = 0;
	char *instruction_str = (char *)malloc(301 * sizeof(char)); // Including space for the null terminator '\0'

    if (instruction_str == NULL) {
       fprintf(stderr, "Memory allocation failed.\n");
       errState = 5;
        return 1; // Return error code indicating failure
    }

	char *flash_str = (char *)malloc(101 * sizeof(char)); // Including space for the null terminator '\0'

    if (flash_str == NULL) {
    	fprintf(stderr, "Memory allocation failed.\n");
    	errState = 5;
        return 1; // Return error code indicating failure
    }

	RCC_AHB1ENR volatile *pRccClockReg;
	pRccClockReg = ADDR_RCC_AHB1ENR;

	GPIOx_MODER volatile *pGpiodModeReg;
	pGpiodModeReg = ADDR_GPIOD_MODER;

	GPIOx_ODR  *pGpiodOutReg;
	pGpiodOutReg = ADDR_GPIOD_ODR;

	GPIOx_IDR volatile *pGpiodInReg;
	pGpiodInReg = ADDR_GPIOD_IDR;

	GPIOx_PUPDR volatile *pGpiodPullUpReg;
	pGpiodPullUpReg = ADDR_GPIOD_PUPDR;


	pRccClockReg->gpiod_en = STATE_ENABLED;
	//Output for PD0 - PD3 Columns
	pGpiodModeReg->moder_0 = MODE_OUTPUT;
	pGpiodModeReg->moder_1 = MODE_OUTPUT;
	pGpiodModeReg->moder_2 = MODE_OUTPUT;
	pGpiodModeReg->moder_3 = MODE_OUTPUT;
	//Input for PD8 - PD11 Rows
	pGpiodModeReg->moder_8 = MODE_INPUT;
	pGpiodModeReg->moder_9 = MODE_INPUT;
	pGpiodModeReg->moder_10 = MODE_INPUT;
	pGpiodModeReg->moder_11 = MODE_INPUT;
	//Output for PD12 - PD15 LEDs
	pGpiodModeReg->moder_12 = MODE_OUTPUT;
	pGpiodModeReg->moder_13 = MODE_OUTPUT;
	pGpiodModeReg->moder_14 = MODE_OUTPUT;
	pGpiodModeReg->moder_15 = MODE_OUTPUT;
	// Pull up registers for PD8-PD11
	pGpiodPullUpReg->pupdr_8 = STATE_ENABLED;
	pGpiodPullUpReg->pupdr_9 = STATE_ENABLED;
	pGpiodPullUpReg->pupdr_10 = STATE_ENABLED;
	pGpiodPullUpReg->pupdr_11 = STATE_ENABLED;


	//Check which button is pressed based on the Row and Column States
	while(1){
	// make rows high
	// clear R1
	pGpiodOutReg->odr_0 = STATE_LOW;
	pGpiodOutReg->odr_1 = STATE_HIGH;
	pGpiodOutReg->odr_2 = STATE_HIGH;
	pGpiodOutReg->odr_3 = STATE_HIGH;


	// C1 PD8
	if(!(pGpiodInReg->idr_8 == STATE_HIGH)){

				blue_dah(pGpiodOutReg);
				printf("1\n");
				instruction_str = addCharToString(instruction_str,'1');
	}
	// C2 PD9
	if(!(pGpiodInReg->idr_9 == STATE_HIGH)){

				blue_dah(pGpiodOutReg);
				printf("2\n");
				instruction_str = addCharToString(instruction_str,'2');
			}
	// C3 PD10
	if(!(pGpiodInReg->idr_10 == STATE_HIGH)){
				blue_dah(pGpiodOutReg);
				printf("3\n");
				instruction_str = addCharToString(instruction_str,'3');

			}
	// C4 PD11
	if(!(pGpiodInReg->idr_11 == STATE_HIGH)){
		// Performs transformation operations of the instruction string and executes the flash string in morse code flashes
				blue_dah(pGpiodOutReg);
				printf("A\n");
				for (int i = 0; i < strlen(instruction_str); i++) {
				        if (!(instruction_str[i] >= '0' && instruction_str[i] <= '9') && instruction_str[i] != '#' && instruction_str[i] != '*') {
				        	instruction_str[i] = '\0'; // Replace junk characters with null terminators
				        }
				    }
				flash_str = createFlashStr(instruction_str);
				flash(flash_str,pGpiodOutReg);

				    // Print the modified string containing only the actual string
				    printf("%s\n", instruction_str);
				    printf("%s\n", flash_str);

				    clearString(instruction_str);
				    clearString(flash_str);

			}
	//
	// make rows high
	// clear R1
	pGpiodOutReg->odr_0 = STATE_HIGH;
	pGpiodOutReg->odr_1 = STATE_LOW;
	// C1 PD8
	if(!(pGpiodInReg->idr_8 == STATE_HIGH)){


				blue_dah(pGpiodOutReg);
				printf("4\n");
				instruction_str = addCharToString(instruction_str,'4');
	}
	// C2 PD9
	if(!(pGpiodInReg->idr_9 == STATE_HIGH)){


				blue_dah(pGpiodOutReg);
				printf("5\n");
				instruction_str = addCharToString(instruction_str,'5');
			}
	// C3 PD10
	if(!(pGpiodInReg->idr_10 == STATE_HIGH)){

				blue_dah(pGpiodOutReg);
				printf("6\n");
				instruction_str = addCharToString(instruction_str,'6');

			}
	// C4 PD11
	if(!(pGpiodInReg->idr_11 == STATE_HIGH)){
		// Acts as a reset
				reset_flash(pGpiodOutReg);
				printf("B\n");
				clearString(instruction_str);
				clearString(flash_str);
				errState = 0;
			}
	//
	// make rows high
	// clear R1

	pGpiodOutReg->odr_1 = STATE_HIGH;
	pGpiodOutReg->odr_2 = STATE_LOW;


	// C1 PD8
	if(!(pGpiodInReg->idr_8 == STATE_HIGH)){

				blue_dah(pGpiodOutReg);
				printf("7\n");
				instruction_str = addCharToString(instruction_str,'7');
	}
	// C2 PD9
	if(!(pGpiodInReg->idr_9 == STATE_HIGH)){

				blue_dah(pGpiodOutReg);
				printf("8\n");
				instruction_str = addCharToString(instruction_str,'8');
			}
	// C3 PD10
	if(!(pGpiodInReg->idr_10 == STATE_HIGH)){
				blue_dah(pGpiodOutReg);
				printf("9\n");
				instruction_str = addCharToString(instruction_str,'9');

			}
	// C4 PD11
	if(!(pGpiodInReg->idr_11 == STATE_HIGH)){
		// Clears the instruction string
				blue_dah(pGpiodOutReg);
				printf("C\n");
				clearString(instruction_str);
			}
	//
	// make rows high
	// clear R1
	pGpiodOutReg->odr_2 = STATE_HIGH;
	pGpiodOutReg->odr_3 = STATE_LOW;


	// C1 PD8
	if(!(pGpiodInReg->idr_8 == STATE_HIGH)){

				blue_dah(pGpiodOutReg);
				printf("*\n");
				instruction_str = addCharToString(instruction_str,'*');
	}
	// C2 PD9
	if(!(pGpiodInReg->idr_9 == STATE_HIGH)){

				blue_dah(pGpiodOutReg);
				printf("0\n");
				instruction_str = addCharToString(instruction_str,'0');

			}
	// C3 PD10
	if(!(pGpiodInReg->idr_10 == STATE_HIGH)){
				blue_dah(pGpiodOutReg);
				printf("#\n");
				instruction_str = addCharToString(instruction_str,'#');

			}
	// C4 PD11
	if(!(pGpiodInReg->idr_11 == STATE_HIGH)){
		// Deletes the last character in the instruction string
				blue_dah(pGpiodOutReg);
				printf("D\n");
				clearLastCharacter(instruction_str);

			}
	if(errState){

	pGpiodOutReg->odr_0 = STATE_HIGH;
	pGpiodOutReg->odr_1 = STATE_LOW;
	pGpiodOutReg->odr_2 = STATE_HIGH;
	pGpiodOutReg->odr_3 = STATE_HIGH;

		while(errState){
			err_flash(pGpiodOutReg);

		if(!(pGpiodInReg->idr_11 == STATE_HIGH)){
			// Acts as a reset
			reset_flash(pGpiodOutReg);
			printf("B\n");
			clearString(instruction_str);
			clearString(flash_str);
			errState = 0;
			}

		}
	}
	//
	}
}
